chapter 6

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -1,6 +1,11 @@
 name: Commit Stage  # The name of the workflow
 on: push            # The workflow is triggered when new code is pushed to the repository.
 
+env:
+  REGISTRY: ghcr.io  # Uses the GitHub Container Registry
+  IMAGE_NAME: anatolyageev/catalog-service # The name of the image. Remember to add your GitHub username, all in lowercase.
+  VERSION: latest # For the moment, any new image will be tagged as “latest”.
+
 jobs:
   build:
     name: Build and Test      # The job’s unique identifier
@@ -17,8 +22,8 @@ jobs:
           distribution: temurin       #
           java-version: 17            #
           cache: gradle               #
-      - name: Build, unit tests and integration tests
-        run: |
+      - name: Build, unit tests and integration tests # Ensures the Gradle wrapper is executable, solving Windows incompatibilities
+        run: |                                        # Runs the Gradle build task, which compiles the codebase and runs unit and integration tests
           chmod +x gradlew
           ./gradlew build
       - name: Code vulnerability scanning
@@ -33,7 +38,46 @@ jobs:
         if: success() || failure()                    # Uploads the report even if the previous step fails
         with:
           sarif_file: ${{ steps.scan.outputs.sarif }} # Fetches the report from the output of the previous step
-      - name: Build, unit tests and integration tests  # Ensures the Gradle wrapper is executable, solving Windows incompatibilities
-        run: |                                        # Runs the Gradle build task, which compiles the codebase and runs unit and integration tests
-            chmod +x gradlew
-            ./gradlew build
+  package:  # The job’s unique identifier
+    name: Package and Publish
+    if: ${{ github.ref == 'refs/heads/main' }} # Runs the job only on the main branch
+    needs: [ build ]                           # Runs the job only if the “build” job completes successfully
+    runs-on: ubuntu-22.04                      # Runs the job on an Ubuntu 22.04 machine
+    permissions:
+      contents: read                           # Permission to check out the current Git repository
+      packages: write                          # Permission to upload images to GitHub Container Registry
+      security-events: write                   # Permission to submit security events to GitHub
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v4              # Checks out the current Git repository (catalog-service)
+      - name: Set up JDK
+        uses: actions/setup-java@v4            # Installs and configures a Java runtime
+        with:
+          distribution: temurin
+          java-version: 17
+          cache: gradle
+      - name: Build container image            # Relies on the Buildpacks integration in Spring Boot to build a container image and defines the name for the release candidate
+        run: |
+          chmod +x gradlew
+          ./gradlew bootBuildImage \             
+            --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+      - name: OCI image vulnerability scanning
+        uses: anchore/scan-action@v3           # Scans the release candidate image for vulnerabilities using grype
+        id: scan
+        with:                                  # The image to scan is the release candidate.
+          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+          fail-build: false                    # It won’t fail the build if vulnerabilities are found in the image.
+          severity-cutoff: high
+      - name: Upload vulnerability report
+        uses: github/codeql-action/upload-sarif@v3  # Uploads the security vulnerability report to GitHub (SARIF format)
+        if: success() || failure()
+        with:
+          sarif_file: ${{ steps.scan.outputs.sarif }}
+      - name: Log into container registry
+        uses: docker/login-action@v3             # Authenticates with GitHub Container Registry
+        with:
+          registry: ${{ env.REGISTRY }}          # The registry value as defined in the environment variable earlier
+          username: ${{ github.actor }}          # The GitHub username of the current user, provided by GitHub Actions
+          password: ${{ secrets.GITHUB_TOKEN }}  # The token needed to authenticate with the registry, provided by GitHub Actions
+      - name: Publish container image            # Pushes the release candidate to the registry
+        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
